# Generated by Django 6.0.3 on 2026-03-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
